create cart page/functionality
Nikitonskii/train pull request #8
Opened 2021-09-06 10:16 UTC by Nikitonskii

2021-09-07 10:08 UTC, twixDuo requested changes

2021-09-07 10:08 UTC, twixDuo commented on src/components/CartItem/index.tsx
> +import CartItem from "./CartItem";
I think better will be, if you ```import``` change to ```export default``` for your component

2021-09-07 10:08 UTC, twixDuo commented on src/components/Header/Header.tsx
> +            {addedProducts.length && (
What you think if we create const with name ```const isEmptyCart = addedProducts.length``` and then we will take name this const

2021-09-07 10:08 UTC, twixDuo commented on src/pages/productsList/ProductsList.tsx
> +                  <ProductCard
Why you repeat this code ? and add only one new key ```cargo_capacity``` What do you think, can you do without repeat this code ?

2021-09-07 10:08 UTC, twixDuo commented on src/store/reducers/cartReducer/index.ts
> +            (item) => item.created !== action.created,
Why you don't add type for item ?

2021-09-07 10:08 UTC, twixDuo commented on src/store/reducers/cartReducer/index.ts
> +            (item) => item.created !== action.created,
And why you use spred ? if filter return new array, and you can write 
```
addedProducts: state.addedProducts.filter((item) => item.created !== action.created)
```

2021-09-07 10:08 UTC, twixDuo commented on src/types/products.ts
> +  name?: string;
why all keys with ```?``` ?

2021-09-07 10:24 UTC, twixDuo requested changes

2021-09-07 10:24 UTC, twixDuo commented on src/components/CartItem/CartItem.tsx
> +  const deleteProduct = (id: string | number) =>
Why ```id``` has type ```string | number``` ?

2021-09-07 10:24 UTC, twixDuo commented on src/components/CartItem/CartItem.tsx
> +      <button onClick={() => deleteProduct(created)}>Delete from cart</button>
Here you pass key ```create```, but this function wait ```id```, where is logic ?)

2021-09-18 14:58 UTC, merged

2023-08-15 09:23 UTC, nikitonskii commented on src/components/CartItem/index.tsx
> +import CartItem from "./CartItem";
```ts
const a: any = 'Hello world'
```